apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: foo
  namespace: crossplane-system
spec:
  references:
  # Use patchesFrom to patch field from other k8s resource to this object
  - patchesFrom:
      apiVersion: v1
      kind: ConfigMap
      name: bar
      namespace: crossplane-system
      fieldPath: data.sample-key
    toFieldPath: data.sample-key-from-bar
  forProvider:
    manifest:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        namespace: crossplane-system
      data:
        sample-key: sample-value
  providerConfigRef:
    name: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bar
  namespace: crossplane-system
data:
  sample-key: sample-value
